apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - name: api
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}